name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [{% for i in range(cookiecutter.python_version[-1] | int, 10) %}"3.{{i}}"{% if not loop.last %}, {% endif %}{% endfor %}]
        poetry-version: [1.1.4]
        os: [ubuntu-18.04]
{% raw %}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}

      - name: Install dependencies
        run: python -m poetry install

      - name: Test with pytest
        run: |
          python -m poetry run python -m pytest -v tests
{% endraw %}
